TARGET?=/srv/www
FILENAME?=my-list.html
TFILE?=/tmp/BLIZZARD_APIKEY.txt

run:
	export BLIZZARD_APIKEY=`cat ${TFILE}`; lein run chars > ${TARGET}/${FILENAME}

token:
	# this should be valid for 24h
	curl -u "xxx:yyy" -d grant_type=client_credentials https://eu.battle.net/oauth/token | jq .access_token | sed 's/"//g' > ${TFILE}

my-list:
	FILENAME=my-list.html make

